-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
LOCATION_MAPPING = {
    [00000] = {"@Golden Chests/B. Wand Chest/"},
    [00001] = {"@Golden Chests/B.B. Wand Chest/"},
	[00002] = {},
	[00003] = {"@Golden Chests/Yoyo Chest/"},
	[00004] = {"@Golden Chests/Slink Chest/"},
	[00005] = {"@Golden Chests/Animal Flute Chest/"},
	[00006] = {"@Golden Chests/Top Chest/"},
	[00007] = {"@Golden Chests/Lantern Chest/"},
	[00008] = {"@Golden Chests/UV Lantern Chest/"},
	[00009] = {"@Golden Chests/B. Ball Chest/"},
	[00010] = {"@Golden Chests/Remote Chest/"},
	[00011] = {"@Golden Chests/Wheel Chest/"},
	
	[00012] = {"@Golden Chests/Mock Disc Chest/"},
	[00013] = {"@Golden Chests/F. Pack Chest/"},
	
	[00014] = {"@Match Chests/Match in Tutorial Chest/"},
	[00015] = {"@Match Chests/Match in Fish Mural Room Chest/"},
	[00016] = {"@Match Chests/Match in Switch-Bounce Room Chest/"},
	[00017] = {"@Match Chests/Match by Dog Fish Pipe Chest/"},
	[00018] = {"@Match Chests/Match in Bear Area/"},
	[00019] = {"@Match Chests/Match Above Egg Room/"},
	[00020] = {"@Match Chests/Match in Center Well Chest/"},
	[00021] = {"@Match Chests/Match in Guard Room Chest/"},
	[00022] = {"@Match Chests/Match under Mouse Statue/"},
	
	[00023] = {"@Key Chests/Key Chest in Lower Bear/"},
	[00024] = {"@Key Chests/Key Chest in Upper Bear/"},
	[00025] = {"@Key Chests/Key Chest by Mouse Head Hitting Lever/"},
	[00026] = {"@Key Chests/Key Chest in West Frog Guard Room/"},
	[00027] = {"@Key Chests/Key Chest in East Frog Guard Room/"},
	[00028] = {"@Key Chests/Key Chest in Dog with Chinchilla Crank/"},
	[00029] = {"@Key Chests/House Key/"},
	[00030] = {"@Key Chests/Office Key Chest/UL D R D UL D R D\nUL DL DR DL UL DL DR DL\nUR L D L UR L D L \nU L DR L U L DR L\nUL D R D UL D R D\nUL DL DR DL UL DL DR DL\nUL UR UL DL UR U L D\nU UL DL L U UL L UL"},
	
	[00031] = {"@Golden Chests/E. Medal Chest/"},
	[00032] = {"@Golden Chests/S. Medal Chest/"},
	--[00033] = {"@Golden Chests/K. Medal Chest/"},
	
	[00034] = {"@Flames/B. Flame/"},
	[00035] = {"@Flames/G. Flame/"},
	[00036] = {"@Flames/V. Flame/"},
	[00037] = {"@Flames/P. Flame/"},
	
	[00038] = {"@Egg Chests/Reference Egg Chest/"},
	[00039] = {"@Egg Chests/Brown Egg Chest/"},
	[00040] = {"@Egg Chests/Raw Egg Chest/"},
	[00041] = {"@Egg Chests/Pickled Egg Chest/"},
	[00042] = {"@Egg Chests/Big Egg Chest/"},
	[00043] = {"@Egg Chests/Swan Egg Chest/"},
	[00044] = {"@Egg Chests/Forbidden Egg Chest/"},
	[00045] = {"@Egg Chests/Shadow Egg Chest/"},
	[00046] = {"@Egg Chests/Vanity Egg Chest/"},
	[00047] = {"@Egg Chests/Egg As A Service Chest/"},
	
	[00048] = {"@Egg Chests/Depraved Egg Chest/"},
	[00049] = {"@Egg Chests/Chaos Egg Chest/"},
	[00050] = {"@Egg Chests/Upside Down Egg Chest/"},
	[00051] = {"@Egg Chests/Evil Egg Chest/"},
	[00052] = {"@Egg Chests/Sweet Egg Chest/"},
	[00053] = {"@Egg Chests/Chocolate Egg Chest/"},
	[00054] = {"@Egg Chests/Value Egg Chest/"},
	[00055] = {"@Egg Chests/Plant Egg Chest/"},
	[00056] = {"@Egg Chests/Red Egg Chest/"},
	[00057] = {"@Egg Chests/Orange Egg Chest/"},
	[00058] = {"@Egg Chests/Sour Egg Chest/"},
	[00059] = {"@Egg Chests/Post Modern Egg Chest/"},
	
	[00060] = {"@Egg Chests/Universal Basic Egg Chest/"},
	[00061] = {"@Egg Chests/Laissez-faire Egg Chest/"},
	[00062] = {"@Egg Chests/Zen Egg Chest/"},
	[00063] = {"@Egg Chests/Future Egg Chest/"},
	[00064] = {"@Egg Chests/Friendship Egg Chest/"},
	[00065] = {"@Egg Chests/Truth Egg Chest/"},
	[00066] = {"@Egg Chests/Transcendental Egg Chest/"},
	[00067] = {"@Egg Chests/Ancient Egg Chest/"},
	[00068] = {"@Egg Chests/Magic Egg Chest/"},
	[00069] = {"@Egg Chests/Mystic Egg Chest/"},
	[00070] = {"@Egg Chests/Holiday Egg Chest/"},
	[00071] = {"@Egg Chests/Rain Egg Chest/"},
	[00072] = {"@Egg Chests/Razzle Egg Chest/"},
	[00073] = {"@Egg Chests/Dazzle Egg Chest/"},
	
	[00074] = {"@Egg Chests/Virtual Egg Chest/"},
	[00075] = {"@Egg Chests/Normal Egg Chest/"},
	[00076] = {"@Egg Chests/Great Egg Chest/"},
	[00077] = {"@Egg Chests/Gorgeous Egg Chest/"},
	[00078] = {"@Egg Chests/Planet Egg Chest/"},
	[00079] = {"@Egg Chests/Moon Egg Chest/"},
	[00080] = {"@Egg Chests/Galaxy Egg Chest/"},
	[00081] = {"@Egg Chests/Sunset Egg Chest/"},
	[00082] = {"@Egg Chests/Goodnight Egg Chest/"},
	[00083] = {"@Egg Chests/Dream Egg Chest/"},
	[00084] = {"@Egg Chests/Travel Egg Chest/"},
	[00085] = {"@Egg Chests/Promise Egg Chest/"},
	[00086] = {"@Egg Chests/Ice Egg Chest/"},
	[00087] = {"@Egg Chests/Fire Egg Chest/"},
	
	[00088] = {"@Egg Chests/Bubble Egg Chest/"},
	[00089] = {"@Egg Chests/Desert Egg Chest/"},
	[00090] = {"@Egg Chests/Clover Egg Chest/"},
	[00091] = {"@Egg Chests/Brick Egg Chest/"},
	[00092] = {"@Egg Chests/Neon Egg Chest/"},
	[00093] = {"@Egg Chests/Iridescent Egg Chest/"},
	[00094] = {"@Egg Chests/Rust Egg Chest/"},
	[00095] = {"@Egg Chests/Scarlet Egg Chest/"},
	[00096] = {"@Egg Chests/Sapphire Egg Chest/"},
	[00097] = {"@Egg Chests/Ruby Egg Chest/"},
	[00098] = {"@Egg Chests/Jade Egg Chest/"},
	[00099] = {"@Egg Chests/Obsidian Egg Chest/"},
	[00100] = {"@Egg Chests/Crystal Egg Chest/"},
	[00101] = {"@Egg Chests/Golden Egg Chest/"},
	
	[00102] = {"@Egg Chests/65th Egg Chest/"},
	
	[00103] = {"@Golden Chests/Map Chest/"},
	[00104] = {"@Golden Chests/Stamp Chest/"},
	[00105] = {"@Golden Chests/Pencil Chest/"},
	
	[00106] = {"@Secret Bunnies/Community Bunny/"},
	[00107] = {"@Secret Bunnies/Chinchilla Bunny/R UR R D R DL DL R"},
	[00108] = {"@Secret Bunnies/Water Spike Bunny/"},
	[00109] = {"@Secret Bunnies/Doodle Bunny/UL U DR D DL D L D"},
	[00110] = {"@Secret Bunnies/Invisible Bunny/"},
	[00111] = {"@Secret Bunnies/Fish Bunny/L L DR R UR L L UR"},
	[00112] = {"@Secret Bunnies/Evil Bunny/R DR D DL L UL U UR"},
	[00113] = {"@Secret Bunnies/Singing Bunny/"},
	[00114] = {"@Secret Bunnies/Green Bunny/U D U D L R L R"},
	[00115] = {"@Secret Bunnies/Imaginary Bunny/"},
	[00116] = {"@Secret Bunnies/Flowering Bunny/R D L U R D UL UR R D L U DR DL UL UR"},
	[00117] = {"@Secret Bunnies/Lava Bunny/"},
	[00118] = {"@Secret Bunnies/Flashing Bunny/UR UL DL DR U L D R"},
	[00119] = {"@Secret Bunnies/Paper Bunny/R UR U L UL U L D"},
	[00120] = {"@Secret Bunnies/Ghost Bunny/"},
	[00121] = {"@Secret Bunnies/Disc Spike Bunny/"},
	
	[00122] = {"@Candles/Squirrel First Candle/"},
	[00123] = {"@Candles/Dog Dark Room Candle/"},
	[00124] = {"@Candles/Dog Boxed Candle/"},
	[00125] = {"@Candles/Dog Candle in Many Switches Room/"},
	[00126] = {"@Candles/Dog Candle in Disc Switch Maze/"},
	[00127] = {"@Candles/Dog Candle in Bat Room/"},
	[00128] = {"@Candles/Fish Candle in Penguin Room/"},
	[00129] = {"@Candles/Frog Switch Candle Carousel/"},
	[00130] = {"@Candles/Bear Candle in Dark Maze/"},
	
	[00131] = {"@Item Chests/Mamma Cha Chest/R UR U L UL U L D"},
}
